# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 83c12d855e7af83e2bb43c6bdc679e97bc61f381d429378986c4c31f1e931e49359a80ad73417cb60763ea92927385ecdb3add37cd0710ad54332517d95dfe05

test:
  secret_key_base: 2489289dc8e869df7157c563ca5be9cb9208dd1db80fb76a6d024c03a1f7a88ecc40d001ba53ebac73212b572737f9bb75ce75e2c12a316b03e650a84a301997

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
